// packages/grid-examples/vue-grid-examples/src/examples/localData/LocalDataExampleRenderer.vue
<script setup lang="ts">
import ErrorMessage from "#shared/ErrorMessage.vue";
import LocalDataEditor from "#examples/localData/LocalDataEditor.vue";
import type { ExampleRendererComponent } from "#examples/types.ts";
import {
  type LocalDataExampleRender,
  useMountLocalDataExample,
} from "#examples/localData/useMountLocalDataExample.ts";

import { getLocalDataEditorEnabled } from "@jsoc/grid-examples-core";

const props = defineProps<{
  component: ExampleRendererComponent;
  render: LocalDataExampleRender;
}>();

const { data, error } = useMountLocalDataExample(props.render);
const showEditor = getLocalDataEditorEnabled();
</script>

<template>
  <div v-if="!data" class="message">No data</div>
  <ErrorMessage v-else-if="error" :error="error" />
  <component v-else-if="data" :is="component" :key="data" :data="data" />
  <LocalDataEditor v-if="showEditor" />
</template>

// packages/grid-examples/react-grid-examples/src/examples/localData/LocalDataExampleRenderer.tsx
import { LocalDataEditor } from "#examples/localData/LocalDataEditor.tsx";
import { useGetLocalData } from "#examples/localData/useLocalData.ts";
import type { ExampleRendererComponent } from "#examples/types.ts";
import { ErrorBoundary } from "#shared/ErrorBoundary.tsx";

import { getLocalDataEditorEnabled } from "@jsoc/grid-examples-core";

export type LocalDataExampleRendererProps = {
  component: ExampleRendererComponent;
};

export function LocalDataExampleRenderer({
  component: Component,
}: LocalDataExampleRendererProps) {
  const data = useGetLocalData();
  const showEditor = getLocalDataEditorEnabled();
  const editorEl = showEditor ? <LocalDataEditor /> : null;

  if (!data)
    return (
      <>
        <div className="message">No data</div>
        {editorEl}
      </>
    );

  return (
    <>
      <ErrorBoundary resetKeys={[data]}>
        <Component data={data} />
      </ErrorBoundary>
      {editorEl}
    </>
  );
}
