// examples/vue-grid/ag/src/examples/Basic.vue
<script setup lang="ts">
import AgGridVue from "../components/AgGridVue.vue";
import { GridStoreProvider, useGridStoreSelector } from "@jsoc/vue-grid";
import { useGridStore } from "@jsoc/vue-grid-ag";
import { shoeJSON } from "@jsoc/grid-examples-shared";

const gridStore = useGridStore(shoeJSON);
const activeSchema = useGridStoreSelector(gridStore, (store) =>
  store.getActiveSchema(),
);
</script>

<template>
  <GridStoreProvider :value="gridStore">
    <div class="example-grid">
      <AgGridVue :key="activeSchema.id" v-bind="activeSchema.config" />
    </div>
  </GridStoreProvider>
</template>

// examples/react-grid/ant/src/examples/Basic.tsx
import { GridStoreProvider, useGridStoreSelector } from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-ant";
import { shoeJSON } from "@jsoc/grid-examples-shared";
import { Table } from "antd";

export function Basic() {
  const gridStore = useGridStore(shoeJSON);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );

  return (
    <GridStoreProvider value={gridStore}>
      <Table key={activeSchema.id} {...activeSchema.config} />
    </GridStoreProvider>
  );
}
