// examples/vue-grid/tanstack/src/examples/basic/Basic.vue
<script setup lang="ts">
import TanStackTable from "#components/TanStackTable.vue";
import { basicJSON as data } from "@jsoc/grid-examples-core";
// <snippet import>
import { useGridStoreSelector } from "@jsoc/vue-grid";
import { useGridStore } from "@jsoc/vue-grid-tanstack";
// </snippet>

// <snippet create>
const gridStore = useGridStore(data);
const activeSchema = useGridStoreSelector(gridStore, (store) =>
  store.getActiveSchema(),
);
// </snippet>
</script>

<template>
  <!-- <snippet render> -->
  <TanStackTable :key="activeSchema.id" :config="activeSchema.config" />
  <!-- </snippet> -->
</template>

// examples/react-grid/ant/src/examples/Basic.tsx
import { AntTable } from "#components/AntTable.tsx";
import { basicJSON as data } from "@jsoc/grid-examples-core";
// <snippet import>
import { useGridStoreSelector } from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-ant";
// </snippet>

export default function BasicExample() {
  // <snippet create>
  const gridStore = useGridStore(data);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );
  // </snippet>

  return (
    // <snippet render>
    <AntTable key={activeSchema.id} {...activeSchema.config} />
    // </snippet>
  );
}
