// examples/vue-grid/tanstack/src/examples/remote-data/RemoteData.vue
<script setup lang="ts">
import RemoteDataExample from "#/examples/remote-data/RemoteDataExample.vue";
import { useGetRemoteJSON } from "@jsoc/vue-grid-examples";

const { data, loading, error } = useGetRemoteJSON();
</script>

<template>
  <p v-if="loading">Loading...</p>
  <p v-else-if="error instanceof Error">Error: {{ error.message }}</p>
  <p v-else-if="!data">No data</p>
  <RemoteDataExample v-else :data="data" />
</template>

// examples/react-grid/ant/src/examples/RemoteData.tsx
import { useGetRemoteJSON } from "@jsoc/react-grid-examples";
import {
  GridStoreProvider,
  SimpleNavigator,
  useGridStoreSelector,
} from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-ant";
import { Table } from "antd";

export function RemoteData() {
  const { data, loading, error } = useGetRemoteJSON();

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;
  if (!data) return <p>No data</p>;

  return <Example data={data} />;
}

function Example({ data }: { data: string }) {
  const gridStore = useGridStore(data);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );

  return (
    <GridStoreProvider value={gridStore}>
      <SimpleNavigator />
      <Table key={activeSchema.id} {...activeSchema.config} />
    </GridStoreProvider>
  );
}
