// packages/grid-examples/react-grid-examples/src/examples/localData/LocalDataExampleRenderer.tsx
import { useGetLocalData } from "#examples/localData/useLocalData.ts";
import type { ExampleRendererComponent } from "#examples/types.ts";
import { ErrorBoundary } from "#shared/ErrorBoundary.tsx";

export type LocalDataExampleRendererProps = {
  component: ExampleRendererComponent;
};

export function LocalDataExampleRenderer({
  component: Component,
}: LocalDataExampleRendererProps) {
  const data = useGetLocalData();

  if (!data) return "No data";

  return (
    <ErrorBoundary resetKeys={[data]}>
      <Component data={data} />
    </ErrorBoundary>
  );
}

// packages/vue-grid-examples/src/examples/localData/LocalDataExampleRenderer.vue
<script setup lang="ts">
import ErrorMessage from "#shared/ErrorMessage.vue";
import type { ExampleRendererComponent } from "#examples/types.ts";
import {
  type LocalDataExampleRender,
  useMountLocalDataExample,
} from "#examples/localData/useMountLocalDataExample.ts";

const props = defineProps<{
  component: ExampleRendererComponent;
  render: LocalDataExampleRender;
}>();

const { data, error } = useMountLocalDataExample(props.render);
</script>

<template>
  <p v-if="!data">No data</p>
  <ErrorMessage v-else-if="error" :error="error" />
  <component v-else :is="component" :key="data" :data="data" />
</template>
