// packages/grid-examples/react-grid-examples/src/examples/localData/LocalDataEditor.tsx
import "@jsoc/grid-examples-core/css/local-data-editor.css";

import {
  useGetLocalData,
  useSetLocalData,
} from "#examples/localData/useLocalData.ts";

import { useState } from "react";

/** JSON editor for standalone local data examples. */
export function LocalDataEditor() {
  const [isOpen, setIsOpen] = useState(false);
  const localData = useGetLocalData();
  const [draft, setDraft] = useState(localData);

  useSetLocalData(draft);

  return (
    <div className="local-data-editor">
      {isOpen && (
        <textarea
          className="local-data-editor__textarea"
          aria-label="Local JSON data"
          placeholder="Enter JSON"
          spellCheck={false}
          value={draft ?? ""}
          onChange={(event) => setDraft(event.target.value)}
        />
      )}
      <button
        type="button"
        className={
          isOpen
            ? "local-data-editor__toggle local-data-editor__toggle--close"
            : "local-data-editor__toggle local-data-editor__toggle--edit"
        }
        aria-label={isOpen ? "Close JSON editor" : "Edit local JSON data"}
        onClick={() => setIsOpen((open) => !open)}
      />
    </div>
  );
}

// packages/grid-examples/vue-grid-examples/src/examples/localData/LocalDataEditor.vue
<script setup lang="ts">
import {
  useGetLocalData,
  useSetLocalData,
} from "#examples/localData/useLocalData.ts";

import "@jsoc/grid-examples-core/css/local-data-editor.css";
import { ref } from "vue";

const isOpen = ref(false);
const localData = useGetLocalData();
const draft = ref(localData.value);

useSetLocalData(draft);
</script>

<template>
  <div class="local-data-editor">
    <textarea
      v-if="isOpen"
      class="local-data-editor__textarea"
      aria-label="Local JSON data"
      placeholder="Enter JSON"
      spellcheck="false"
      :value="draft ?? ''"
      @input="
        draft = ($event.target as HTMLTextAreaElement).value;
      "
    />
    <button
      type="button"
      class="local-data-editor__toggle"
      :class="
        isOpen
          ? 'local-data-editor__toggle--close'
          : 'local-data-editor__toggle--edit'
      "
      :aria-label="isOpen ? 'Close JSON editor' : 'Edit local JSON data'"
      @click="isOpen = !isOpen"
    />
  </div>
</template>
