// packages/vanilla-grid/src/components/ChildGridToggle.tsx
import type {
  ColumnGeneratorParams,
  GridRow,
  PluginConfig,
} from "@jsoc/grid-core";

export type ChildGridToggleOptions<C extends PluginConfig> = {
  row: GridRow;
  columnParams: ColumnGeneratorParams<C, "ujsonObject" | "ujsonObjectArray">;
};

/**
 * Creates a ChildGridToggle button element.
 */
export function ChildGridToggle<C extends PluginConfig>({
  row,
  columnParams,
}: ChildGridToggleOptions<C>): HTMLButtonElement {
  const { columnKey, gridSchema } = columnParams;
  const gridStore = gridSchema.store;
  const origin = gridStore.getChildSchemaOrigin(row, columnKey);
  const toggleStatus = gridStore.hasChildSchema(origin);
  const toggle = () => gridStore.toggleChildSchema(origin);

  return (
    <button type="button" onClick={toggle}>
      {toggleStatus ? "Close" : "View"}
    </button>
  ) as HTMLButtonElement;
}

/**
 * Alias for {@link ChildGridToggle}.
 */
export const createChildGridToggle = ChildGridToggle;

// packages/vue-grid/src/components/ChildGridToggle.vue
<script setup lang="ts" generic="C extends PluginConfig">
import { useGridStoreSelector } from "#composables/index.ts";

import type { ChildGridToggleProps } from "#components/ChildGridToggle.ts";

import type { PluginConfig } from "@jsoc/grid-core";
import { computed } from "vue";

const props = defineProps<ChildGridToggleProps<C>>();

const gridStore = computed(() => props.columnParams.gridSchema.store);
const origin = computed(() =>
  gridStore.value.getChildSchemaOrigin(props.row, props.columnParams.columnKey),
);
const toggleStatus = useGridStoreSelector(gridStore, (store) =>
  store.hasChildSchema(origin.value),
);
const toggle = () => gridStore.value.toggleChildSchema(origin.value);
</script>

<template>
  <slot :toggle="toggle" :toggle-status="toggleStatus">
    <button type="button" @click="toggle">
      {{ toggleStatus ? "Close" : "View" }}
    </button>
  </slot>
</template>
