// packages/react-grid/src/components/GridStoreProvider.tsx
import { GridStoreContext } from "#internals/contexts/GridStoreContext.tsx";

import type { GridStore, PluginConfig } from "@jsoc/grid-core";
import type { ReactNode } from "react";

export type GridStoreProviderProps<C extends PluginConfig> = {
  value: GridStore<C>;
  children: ReactNode;
};

export function GridStoreProvider<C extends PluginConfig>({
  value,
  children,
}: GridStoreProviderProps<C>) {
  return (
    <GridStoreContext.Provider value={value as GridStore}>
      {children}
    </GridStoreContext.Provider>
  );
}

// packages/vue-grid/src/components/GridStoreProvider.vue
<script setup lang="ts" generic="C extends PluginConfig">
import { gridStoreInjectionKey } from "#internals/injection.ts";

import type { GridStore, PluginConfig } from "@jsoc/grid-core";
import { provide, toRef } from "vue";

export type GridStoreProviderProps<C extends PluginConfig> = {
  value: GridStore<C>;
};

const props = defineProps<{
  value: GridStore<C>;
}>();

provide(
  gridStoreInjectionKey,
  toRef(() => props.value as GridStore<PluginConfig>),
);
</script>

<template>
  <slot />
</template>
