// packages/grid-examples/vue-grid-examples/src/router/ExamplesRouter.vue
<script setup lang="ts">
import ExamplesRouterIndexPage from "#router/ExamplesRouterIndexPage.vue";
import type { ExamplesRouterOptions } from "#router/types.ts";
import { useExampleIdSearchParam } from "#router/useExampleIdSearchParam.ts";

import { isValidExampleId } from "@jsoc/grid-docs";

import { computed } from "vue";

const props = defineProps<ExamplesRouterOptions>();

const { exampleId } = useExampleIdSearchParam();

const activeComponent = computed(() => {
  const exampleIdValue = exampleId.value;
  if (
    !exampleIdValue ||
    !isValidExampleId("vue-grid", props.pluginId, exampleIdValue)
  ) {
    return null;
  }

  return props.components[exampleIdValue];
});
</script>

<template>
  <template v-if="activeComponent">
    <component :is="activeComponent" />
  </template>

  <p v-else-if="exampleId">Invalid example ID: "{{ exampleId }}"</p>

  <ExamplesRouterIndexPage v-else :plugin-id="props.pluginId" />
</template>

// packages/react-grid-examples/src/router/ExamplesRouter.tsx
import { ExamplesRouterIndexPage } from "#router/ExamplesRouterIndexPage.tsx";
import type { ExamplesRouterOptions } from "#router/types.ts";

import { isValidExampleId, type ReactGridPluginId } from "@jsoc/grid-docs";
import { readExampleIdSearchParam } from "@jsoc/grid-examples-shared";
import type { FC } from "react";
import {
  BrowserRouter,
  Route,
  Routes,
  useSearchParams,
} from "react-router-dom";

export function ExamplesRouter<P extends ReactGridPluginId>(
  options: ExamplesRouterOptions<P>,
) {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="*" element={<ExampleDispatcher {...options} />} />
      </Routes>
    </BrowserRouter>
  );
}

function ExampleDispatcher<P extends ReactGridPluginId>(
  options: ExamplesRouterOptions<P>,
) {
  const [searchParams] = useSearchParams();
  const exampleId = readExampleIdSearchParam(searchParams);

  if (!exampleId) return <ExamplesRouterIndexPage {...options} />;
  if (!isValidExampleId("react-grid", options.pluginId, exampleId))
    return `Invalid example ID: "${exampleId}"`;

  const Component = options.components[exampleId] as FC;
  return <Component />;
}
