// packages/grid-examples/vue-grid-examples/src/router/ExamplesRouterIndexPage.vue
<script setup lang="ts">
import type { ExamplesRouterOptions } from "#router/types.ts";
import { useExampleIdSearchParam } from "#router/useExampleIdSearchParam.ts";

import {
  buildExampleIdSearchQuery,
  getExampleIds,
  getExampleMetadata,
  getPluginMetadata,
} from "@jsoc/grid-docs";

const props = defineProps<Pick<ExamplesRouterOptions, "pluginId">>();

const { setExampleId } = useExampleIdSearchParam();

const exampleIds = getExampleIds("vue-grid", props.pluginId);
const pluginName = getPluginMetadata("vue-grid", props.pluginId).name;
</script>

<template>
  <nav>
    <h1>{{ pluginName }} x JSOC Grid</h1>
    <ul>
      <li v-for="id in exampleIds" :key="id">
        <a
          :href="buildExampleIdSearchQuery(id)"
          @click.prevent="setExampleId(id)"
        >
          {{ getExampleMetadata("vue-grid", props.pluginId, id).name }}
        </a>
      </li>
    </ul>
  </nav>
</template>

// packages/react-grid-examples/src/router/ExamplesRouterIndexPage.tsx
import type { ExamplesRouterOptions } from "#router/types.ts";

import {
  buildExampleIdSearchQuery,
  getExampleIds,
  getExampleMetadata,
  getPluginMetadata,
  type ReactGridPluginId,
} from "@jsoc/grid-docs";
import { Link } from "react-router-dom";

export function ExamplesRouterIndexPage({
  pluginId,
}: ExamplesRouterOptions<ReactGridPluginId>) {
  const { name } = getPluginMetadata("react-grid", pluginId);
  const exampleIds = getExampleIds("react-grid", pluginId);

  return (
    <nav>
      <h1>{name} x JSOC Grid</h1>
      <ul>
        {exampleIds.map((exampleId) => {
          const { name } = getExampleMetadata(
            "react-grid",
            pluginId,
            exampleId,
          );
          return (
            <li key={exampleId}>
              <Link to={buildExampleIdSearchQuery(exampleId)}>{name}</Link>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
