// packages/vue-grid/src/components/ChildGridToggle.vue
<script setup lang="ts" generic="C extends PluginConfig">
import { useGridStoreSelector } from "#composables/index.ts";

import type { ChildGridToggleProps } from "#components/ChildGridToggle.ts";

import type { PluginConfig } from "@jsoc/grid-core";
import { computed } from "vue";

const props = defineProps<ChildGridToggleProps<C>>();

const gridStore = computed(() => props.columnParams.gridSchema.store);
const origin = computed(() =>
  gridStore.value.getChildSchemaOrigin(props.row, props.columnParams.columnKey),
);
const toggleStatus = useGridStoreSelector(gridStore, (store) =>
  store.hasChildSchema(origin.value),
);
const toggle = () => gridStore.value.toggleChildSchema(origin.value);
</script>

<template>
  <slot :toggle="toggle" :toggle-status="toggleStatus">
    <button type="button" @click="toggle">
      {{ toggleStatus ? "Close" : "View" }}
    </button>
  </slot>
</template>

// packages/react-grid/src/components/ChildGridToggle.tsx
import { useGridStoreSelector } from "#hooks/useGridStoreSelector.ts";

import type {
  ColumnGeneratorParams,
  GridRow,
  PluginConfig,
} from "@jsoc/grid-core";
import type { ReactNode } from "react";

export type ChildGridToggleRenderer = (
  toggle: () => void,
  toggleStatus: boolean,
) => ReactNode;

export type ChildGridToggleProps<C extends PluginConfig> = {
  /**
   * Custom renderer for the toggle action.
   * Defaults to {@link DefaultRenderer}.
   */
  children?: ChildGridToggleRenderer;
  /**
   * The GridRow that contains the cell in which this component will be rendered.
   */
  row: GridRow;
  columnParams: ColumnGeneratorParams<C, "ujsonObject" | "ujsonObjectArray">;
};

export function ChildGridToggle<C extends PluginConfig>({
  children: renderer = DefaultRenderer,
  row,
  columnParams,
}: ChildGridToggleProps<C>) {
  const { columnKey, gridSchema } = columnParams;
  const gridStore = gridSchema.store;
  const origin = gridStore.getChildSchemaOrigin(row, columnKey);
  const toggleStatus = useGridStoreSelector(gridStore, (store) =>
    store.hasChildSchema(origin),
  );
  const toggle = () => gridStore.toggleChildSchema(origin);

  return renderer(toggle, toggleStatus);
}

const DefaultRenderer: ChildGridToggleRenderer = (toggle, toggleStatus) => {
  return <button onClick={toggle}>{toggleStatus ? "Close" : "View"}</button>;
};
