// packages/vue-grid/src/components/SimpleNavigator.vue
<script setup lang="ts" generic="C extends PluginConfig">
import { useGridStoreSelector } from "#composables/index.ts";

import type { SimpleNavigatorProps } from "#components/SimpleNavigator.ts";

import type { PluginConfig } from "@jsoc/grid-core";
import { computed } from "vue";

const props = defineProps<SimpleNavigatorProps<C>>();

const totalChildSchemas = useGridStoreSelector(
  () => props.gridStore,
  (store) => store.getTotalChildSchemas(),
);
const canRemove = computed(() => totalChildSchemas.value > 0);
const removeActiveSchema = () => props.gridStore.removeChildSchema();
</script>

<template>
  <slot :can-remove="canRemove" :remove-active-schema="removeActiveSchema">
    <button type="button" :disabled="!canRemove" @click="removeActiveSchema">
      {{ canRemove ? "Back" : "Root" }}
    </button>
  </slot>
</template>

// packages/react-grid/src/components/SimpleNavigator.tsx
import { useGridStoreSelector } from "#hooks/useGridStoreSelector.ts";

import type { GridStore, PluginConfig } from "@jsoc/grid-core";
import type { ReactNode } from "react";

export type SimpleNavigatorRenderer = (params: {
  canRemove: boolean;
  removeActiveSchema: () => void;
}) => ReactNode;

export type SimpleNavigatorProps<C extends PluginConfig = PluginConfig> = {
  gridStore: GridStore<C>;
  /**
   * Custom Renderer for the SimpleNavigator
   */
  children?: SimpleNavigatorRenderer;
};

export function SimpleNavigator<C extends PluginConfig = PluginConfig>({
  gridStore,
  children: customRenderer,
}: SimpleNavigatorProps<C>) {
  const totalChildSchemas = useGridStoreSelector(gridStore, (store) =>
    store.getTotalChildSchemas(),
  );

  const canRemove = totalChildSchemas > 0;
  const removeActiveSchema = () => gridStore.removeChildSchema();

  if (customRenderer) {
    return customRenderer({ canRemove, removeActiveSchema });
  }

  return (
    <button disabled={!canRemove} onClick={removeActiveSchema}>
      {canRemove ? "Back" : "Root"}
    </button>
  );
}
