// examples/react-grid/tanstack/src/App.tsx
import { Basic, LocalData, RemoteData } from "./examples/";

import { ExamplesRouter } from "@jsoc/react-grid-examples";
import { useDetectColorScheme } from "@jsoc/react-grid-examples";
import { useEffect } from "react";

/**
 * Examples of TanStack Table rendered using JSOC Grid
 * @see {@link https://tanstack.com/table/latest TanStack Table Docs}
 */
export default function App() {
  const colorScheme = useDetectColorScheme();

  useEffect(() => {
    document.documentElement.classList.toggle("dark", colorScheme === "dark");
  }, [colorScheme]);

  return (
    <ExamplesRouter
      pluginId="tanstack"
      components={{
        basic: Basic,
        "local-data": LocalData,
        "remote-data": RemoteData,
      }}
    />
  );
}

// examples/vue-grid/ag/src/App.vue
<script setup lang="ts">
import basic from "#examples/basic/Basic.vue";
import localData from "#examples/local-data/LocalData.vue";
import remoteData from "#examples/remote-data/RemoteData.vue";

import { ExamplesRouter } from "@jsoc/vue-grid-examples";
import { AllCommunityModule, ModuleRegistry } from "ag-grid-community";

ModuleRegistry.registerModules([AllCommunityModule]);
</script>

<template>
  <ExamplesRouter
    plugin-id="ag"
    :components="{ basic, localData, remoteData }"
  />
</template>
