// examples/vue-grid/ag/src/examples/basic/Basic.vue
<script setup lang="ts">
import AgGridVue from "#components/AgGridVue.vue";
import { basicJSON } from "@jsoc/grid-examples-core";
// <snippet import>
import { useGridStoreSelector } from "@jsoc/vue-grid";
import { useGridStore } from "@jsoc/vue-grid-ag";
// </snippet>

// <snippet create>
const gridStore = useGridStore(basicJSON);
const activeSchema = useGridStoreSelector(gridStore, (store) =>
  store.getActiveSchema(),
);
// </snippet>
</script>

<template>
  <!-- <snippet render> -->
  <AgGridVue :key="activeSchema.id" :grid-options="activeSchema.config" />
  <!-- </snippet> -->
</template>

// examples/react-grid/ag/src/examples/Basic.tsx
import { AgGridReact } from "#components/AgGridReact.tsx";
import { basicJSON } from "@jsoc/grid-examples-core";
// <snippet import>
import { useGridStoreSelector } from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-ag";
// </snippet>

export default function BasicExample() {
  // <snippet create>
  const gridStore = useGridStore(basicJSON);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );
  // </snippet>

  return (
    // <snippet render>
    <AgGridReact key={activeSchema.id} {...activeSchema.config} />
    // </snippet>
  );
}
