// examples/vue-grid/ag/src/examples/RemoteData.vue
<script setup lang="ts">
import RemoteDataExample from "./RemoteDataExample.vue";
import { useGetRemoteJSON } from "@jsoc/vue-grid-examples";

const { data, loading, error } = useGetRemoteJSON();
</script>

<template>
  <p v-if="loading">Loading...</p>
  <p v-else-if="error instanceof Error">Error: {{ error.message }}</p>
  <p v-else-if="!data">No data</p>
  <RemoteDataExample v-else :data="data" />
</template>

// examples/react-grid/ag/src/examples/RemoteData.tsx
import { AgGridReact } from "../components/AgGridReact";
import { useGetRemoteJSON } from "@jsoc/react-grid-examples";
import {
  GridStoreProvider,
  SimpleNavigator,
  useGridStoreSelector,
} from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-ag";

export function RemoteData() {
  const { data, loading, error } = useGetRemoteJSON();

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error: {error.message}</p>;
  if (!data) return <p>No data</p>;

  return <Example data={data} />;
}

function Example({ data }: { data: string }) {
  const gridStore = useGridStore(data);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );

  return (
    <GridStoreProvider value={gridStore}>
      <SimpleNavigator />
      <div style={{ height: "calc(100% - 40px)" }}>
        <AgGridReact key={activeSchema.id} {...activeSchema.config} />
      </div>
    </GridStoreProvider>
  );
}
