// packages/grid-examples/vue-grid-examples/src/router/ExamplesRouterIndexPage.vue
<script setup lang="ts">
import type { ExamplesRouterOptions } from "#router/types.ts";
import { useExampleIdSearchParam } from "#router/useExampleIdSearchParam.ts";

import {
  buildExampleIdSearchQuery,
  getExampleIds,
  getExampleMetadata,
  getPluginMetadata,
} from "@jsoc/grid-docs";

const props = defineProps<Pick<ExamplesRouterOptions, "pluginId">>();

const { setExampleId } = useExampleIdSearchParam();

const exampleIds = getExampleIds("vue-grid", props.pluginId);
const pluginName = getPluginMetadata("vue-grid", props.pluginId).name;
</script>

<template>
  <nav>
    <h1>{{ pluginName }} x JSOC Grid</h1>
    <ul>
      <li v-for="id in exampleIds" :key="id">
        <a
          :href="buildExampleIdSearchQuery(id)"
          @click.prevent="setExampleId(id)"
        >
          {{ getExampleMetadata("vue-grid", props.pluginId, id).name }}
        </a>
      </li>
    </ul>
  </nav>
</template>

// packages/grid-examples/vanilla-grid-examples/src/router/ExamplesRouterIndexPage.tsx
import type { ExamplesRouterOptions } from "#router/types.ts";

import {
  buildExampleIdSearchQuery,
  type ExampleId,
  getExampleIds,
  getExampleMetadata,
  getPluginMetadata,
  type PluginId,
  type VanillaGridPluginId,
} from "@jsoc/grid-docs";
import { setExampleIdSearchParam } from "@jsoc/grid-examples-core";

export function ExamplesRouterIndexPage<P extends VanillaGridPluginId>(
  options: ExamplesRouterOptions<P>,
) {
  const { pluginId } = options;
  const { name } = getPluginMetadata("vanilla-grid", pluginId);
  const exampleIds = getExampleIds("vanilla-grid", pluginId);

  return (
    <nav>
      <h1>{name} x JSOC Grid</h1>
      <ul>
        {exampleIds.map((exampleId) => (
          <ExampleLink
            key={exampleId}
            pluginId={pluginId}
            exampleId={exampleId}
          />
        ))}
      </ul>
    </nav>
  ) as HTMLElement;
}

type ExampleLinkProps<P extends PluginId<"vanilla-grid">> = {
  pluginId: P;
  exampleId: ExampleId<"vanilla-grid", P>;
};

function ExampleLink<P extends PluginId<"vanilla-grid">>({
  pluginId,
  exampleId,
}: ExampleLinkProps<P>) {
  const { name: exampleName } = getExampleMetadata(
    "vanilla-grid",
    pluginId,
    exampleId,
  );

  return (
    <li>
      <a
        href={buildExampleIdSearchQuery(exampleId)}
        onClick={(event: Event) => {
          event.preventDefault();
          setExampleIdSearchParam(exampleId);
        }}
      >
        {exampleName}
      </a>
    </li>
  ) as HTMLElement;
}
