// examples/react-grid/tanstack/src/components/TanstackTable.tsx
import "@jsoc/grid-examples-core/css/tanstack-table.css";

import type { GridRow } from "@jsoc/grid-core";
import { flexRender, type Table } from "@tanstack/react-table";

export function TanstackTable({ table }: { table: Table<GridRow> }) {
  const headerGroups = table.getHeaderGroups();
  const rows = table.getRowModel().rows;

  const hasRows = rows.length > 0;
  const hasHeaders = headerGroups.some((group) => group.headers.length > 0);

  if (!hasRows) return <p>No rows</p>;
  if (!hasHeaders) return <p>No columns</p>;

  return (
    // wrapping in <div> with overflow: auto to handle horizontal scrolling,
    // because standard HTML tables do not support overflow properties directly
    <div className="table-wrapper">
      <table>
        <thead>
          {headerGroups.map((hg) => (
            <tr key={hg.id}>
              {hg.headers.map((header) => (
                <th key={header.id}>
                  {flexRender(
                    header.column.columnDef.header,
                    header.getContext(),
                  )}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id}>
              {row.getVisibleCells().map((cell) => (
                <td key={cell.id}>
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// examples/vue-grid/tanstack/src/components/TanStackTable.vue
<script setup lang="ts">
import "@jsoc/grid-examples-core/css/tanstack-table.css";

import type { PluginConfigTanstack } from "@jsoc/vue-grid-tanstack";
import { FlexRender, getCoreRowModel, useVueTable } from "@tanstack/vue-table";
import { computed } from "vue";

const props = defineProps<{
  config: PluginConfigTanstack;
}>();

const table = useVueTable({
  ...props.config,
  getCoreRowModel: getCoreRowModel(),
});

const headerGroups = computed(() => table.getHeaderGroups());
const rows = computed(() => table.getRowModel().rows);
const hasRows = computed(() => rows.value.length > 0);
const hasHeaders = computed(() =>
  headerGroups.value.some((group) => group.headers.length > 0),
);
</script>

<template>
  <p v-if="!hasRows">No rows</p>
  <p v-else-if="!hasHeaders">No columns</p>
  <!-- wrapping in div with overflow: auto to handle horizontal scrolling,
       because standard HTML tables do not support overflow properties directly -->
  <div v-else class="table-wrapper">
    <table>
      <thead>
        <tr v-for="headerGroup in headerGroups" :key="headerGroup.id">
          <th v-for="header in headerGroup.headers" :key="header.id">
            <FlexRender
              v-if="!header.isPlaceholder"
              :render="header.column.columnDef.header"
              :props="header.getContext()"
            />
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in rows" :key="row.id">
          <td v-for="cell in row.getVisibleCells()" :key="cell.id">
            <FlexRender
              :render="cell.column.columnDef.cell"
              :props="cell.getContext()"
            />
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
