// examples/vue-grid/tanstack/src/App.vue
<script setup lang="ts">
import basic from "#examples/basic/Basic.vue";
import localData from "#examples/local-data/LocalData.vue";
import remoteData from "#examples/remote-data/RemoteData.vue";

import { ExamplesRouter } from "@jsoc/vue-grid-examples";
</script>

<template>
  <ExamplesRouter
    plugin-id="tanstack"
    :components="{ basic, localData, remoteData }"
  />
</template>

// examples/react-grid/mantine/src/App.tsx
import { Basic, LocalData, RemoteData } from "./examples/";

import { ExamplesRouter } from "@jsoc/react-grid-examples";
import { useDetectColorScheme } from "@jsoc/react-grid-examples";
import { MantineProvider } from "@mantine/core";

/**
 * Examples of MantineReactTable rendered using JSOC Grid
 * @see {@link https://www.mantine-react-table.com/docs/getting-started/ MantineReactTable Docs}
 */
export default function App() {
  const colorScheme = useDetectColorScheme();

  return (
    <MantineProvider theme={{ colorScheme }}>
      <ExamplesRouter
        pluginId="mantine"
        components={{
          basic: Basic,
          "local-data": LocalData,
          "remote-data": RemoteData,
        }}
      />
    </MantineProvider>
  );
}
