// examples/react-grid/ag/src/examples/LocalData.tsx
import { AgGridReact } from "ag-grid-react";

import { useGridStoreSelector } from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-ag";
import { LocalDataExampleRenderer } from "@jsoc/react-grid-examples";

export default function LocalDataExample() {
  return <LocalDataExampleRenderer component={Example} />;
}

function Example({ data }: { data: string }) {
  const gridStore = useGridStore(data);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );

  return <AgGridReact key={activeSchema.id} {...activeSchema.config} />;
}

// examples/vue-grid/ag/src/examples/LocalData.vue
<script setup lang="ts">
import LocalDataExample from "./LocalDataExample.vue";
import { ErrorBoundary, useGetLocalJSON } from "@jsoc/vue-grid-examples";

const data = useGetLocalJSON();
</script>

<template>
  <p v-if="data === undefined">No data</p>
  <ErrorBoundary v-else :reset-keys="[data]">
    <LocalDataExample :data="data" />
  </ErrorBoundary>
</template>
