// packages/vue-grid-examples/src/shared/ErrorMessage.vue
<script setup lang="ts">
import "@jsoc/grid-examples-shared/css/error-message.css";

import { ensureError } from "@jsoc/utils";
import { computed } from "vue";

const props = defineProps<{
  error: unknown;
}>();

const err = computed(() => ensureError(props.error));
</script>

<template>
  <div class="error-message">
    <p>{{ err.name }}</p>
    <div>
      <pre>{{ err.message }}</pre>
    </div>
  </div>
</template>

// packages/react-grid-examples/src/shared/ErrorMessage.tsx
import "@jsoc/grid-examples-shared/css/error-message.css";

import { ensureError } from "@jsoc/utils";

export function ErrorMessage({ error }: { error: unknown }) {
  const err = ensureError(error);

  return (
    <div className="error-message">
      <p>{err.name}</p>
      <div>
        <pre>{err.message}</pre>
      </div>
    </div>
  );
}
