// packages/grid-examples/react-grid-examples/src/examples/remoteData/RemoteDataExampleRenderer.tsx
import { useFetchRemoteData } from "#examples/remoteData/useFetchRemoteData.ts";
import type { ExampleRendererComponent } from "#examples/types.ts";
import { ErrorMessage } from "#shared/ErrorMessage.tsx";

export type RemoteDataExampleRendererProps = {
  component: ExampleRendererComponent;
};

export function RemoteDataExampleRenderer({
  component: Component,
}: RemoteDataExampleRendererProps) {
  const { data, error, isLoading, isError } = useFetchRemoteData();

  if (isLoading) return "Loading...";
  if (isError) return <ErrorMessage error={error} />;

  return <Component data={data} />;
}

// packages/grid-examples/vue-grid-examples/src/examples/remoteData/RemoteDataExampleRenderer.vue
<script setup lang="ts">
import { useFetchRemoteData } from "#examples/remoteData/useFetchRemoteData.ts";
import ErrorMessage from "#shared/ErrorMessage.vue";
import type { ExampleRendererComponent } from "#examples/types.ts";

defineProps<{
  component: ExampleRendererComponent;
}>();

const state = useFetchRemoteData();
</script>

<template>
  <p v-if="state.isLoading">Loading...</p>
  <ErrorMessage v-else-if="state.isError" :error="state.error" />
  <component v-else :is="component" :key="state.data" :data="state.data" />
</template>
