// examples/react-grid/mui/src/examples/Basic.tsx
import { basicJSON as data } from "@jsoc/grid-examples-core";
// <snippet import>
import { useGridStoreSelector } from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-mui";
// </snippet>
import { DataGrid } from "@mui/x-data-grid";

export default function BasicExample() {
  // <snippet create>
  const gridStore = useGridStore(data);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );
  // </snippet>

  return (
    // <snippet render>
    <DataGrid key={activeSchema.id} {...activeSchema.config} />
    // </snippet>
  );
}

// examples/vue-grid/ag/src/examples/basic/Basic.vue
<script setup lang="ts">
import { AgGridVue } from "ag-grid-vue3";
import { basicJSON as data } from "@jsoc/grid-examples-core";
// <snippet import>
import { useGridStoreSelector } from "@jsoc/vue-grid";
import { useGridStore } from "@jsoc/vue-grid-ag";
// </snippet>

// <snippet create>
const gridStore = useGridStore(data);
const activeSchema = useGridStoreSelector(gridStore, (store) =>
  store.getActiveSchema(),
);
// </snippet>
</script>

<template>
  <!-- <snippet render> -->
  <AgGridVue :key="activeSchema.id" :grid-options="activeSchema.config" />
  <!-- </snippet> -->
</template>
