// examples/react-grid/tanstack/src/App.tsx
import { Basic, LocalData, RemoteData } from "./examples/";

import { ExamplesRouter } from "@jsoc/react-grid-examples";
import { useDetectColorScheme } from "@jsoc/react-grid-examples";
import { useEffect } from "react";

/**
 * Examples of TanStack Table rendered using JSOC Grid
 * @see {@link https://tanstack.com/table/latest TanStack Table Docs}
 */
export default function App() {
  const colorScheme = useDetectColorScheme();

  useEffect(() => {
    document.documentElement.classList.toggle("dark", colorScheme === "dark");
  }, [colorScheme]);

  return (
    <ExamplesRouter
      pluginId="tanstack"
      components={{
        basic: Basic,
        "local-data": LocalData,
        "remote-data": RemoteData,
      }}
    />
  );
}

// examples/vue-grid/tanstack/src/App.vue
<script setup lang="ts">
import { Basic, LocalData, RemoteData } from "#/examples/index.ts";
import { ExamplesRouter, useDetectColorScheme } from "@jsoc/vue-grid-examples";
import { watchEffect } from "vue";

const colorScheme = useDetectColorScheme();

watchEffect(() => {
  document.documentElement.classList.toggle("dark", colorScheme.value === "dark");
});
</script>

<template>
  <ExamplesRouter
    plugin-id="tanstack"
    :components="{
      basic: Basic,
      'local-data': LocalData,
      'remote-data': RemoteData,
    }"
  />
</template>
