// examples/vue-grid/ag/src/examples/local-data/LocalData.vue
<script setup lang="ts">
import LocalDataExample from "#examples/local-data/LocalDataExample.vue";
import { createGridStore } from "@jsoc/vue-grid-ag";
import { LocalDataExampleRenderer } from "@jsoc/vue-grid-examples";

function render(data: string) {
  createGridStore(data);
}
</script>

<template>
  <LocalDataExampleRenderer :component="LocalDataExample" :render="render" />
</template>

// examples/react-grid/mui/src/examples/LocalData.tsx
import { useGridStoreSelector } from "@jsoc/react-grid";
import { useGridStore } from "@jsoc/react-grid-mui";
import { LocalDataExampleRenderer } from "@jsoc/react-grid-examples";
import { DataGrid } from "@mui/x-data-grid";

export default function LocalDataExample() {
  return <LocalDataExampleRenderer component={Example} />;
}

function Example({ data }: { data: string }) {
  const gridStore = useGridStore(data);
  const activeSchema = useGridStoreSelector(gridStore, (gridStore) =>
    gridStore.getActiveSchema(),
  );

  return <DataGrid key={activeSchema.id} {...activeSchema.config} />;
}
